In [3]:
import tensorflow as tf

In [5]:
a=tf.constant([[5,7],[2,1]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 7],
       [2, 1]])>

In [6]:
b=tf.add(a,2)
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 9],
       [4, 3]])>

In [8]:
c=b**2
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[49, 81],
       [16,  9]])>

In [9]:
d=tf.reduce_sum(c)
d

<tf.Tensor: shape=(), dtype=int32, numpy=155>